

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "EntityFramework.Reverse.POCO.Generator\App.config"
//     Connection String Name: "MyDbContextSqlCE4"
//     Connection String:      "Data Source=C:\Dev\github\EntityFramework-Reverse-POCO-Code-First-Generator\EntityFramework.Reverse.POCO.Generator\App_Data\NorthwindSqlCe40.sdf"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to load provider "System.Data.SqlServerCe.4.0".
// -----------------------------------------------------------------------------------------
Unable to find the requested .Net Framework Data Provider.  It may not be installed.
System.ArgumentException
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at Microsoft.VisualStudio.TextTemplatingD6B17638A665491A1339A28F2FC6232C5828090BEE8B59CC7BA24262162D679480AE39931853A8B5587E11DA96792B879B031313DFF55C73FA52FA1789DD1F32.GeneratedTextTransformation.GetDbProviderFactory() in C:\Dev\github\EntityFramework-Reverse-POCO-Code-First-Generator\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.Core.ttinclude:line 661



